const APP_VERSION='1.0.0';
const MAX_FILE=50*1024*1024, MAX_LOGS=20, MAX_PINNED=5, TTL=24*60*60*1000;
const state={mode:'host',localName:localStorage.getItem('c1_localName')||'localuser',peers:new Map(),selectedPeer:'',currentSlot:'',joinPeer:null,deferredPrompt:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const enc=o=>btoa(unescape(encodeURIComponent(JSON.stringify(o))));
const dec=s=>JSON.parse(decodeURIComponent(escape(atob(s.trim()))));
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
const now=()=>Date.now();
function showView(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active'); if(id==='logView') renderLogs();}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view)); $$('[data-back]').forEach(b=>b.onclick=()=>showView('homeView'));

// IndexedDB
let dbp;
function db(){if(!dbp)dbp=new Promise((res,rej)=>{const r=indexedDB.open('connection1toOneDB',1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('logs')) d.createObjectStore('logs',{keyPath:'id'});if(!d.objectStoreNames.contains('files')) d.createObjectStore('files',{keyPath:'id'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}
async function put(store,val){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).put(val);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function getAll(store){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getOne(store,id){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function delOne(store,id){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).delete(id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function cleanup(){let logs=await getAll('logs');const cutoff=now()-TTL;for(const l of logs){if(!l.pinned && l.updatedAt<cutoff){for(const m of l.messages||[]) if(m.fileId) await delOne('files',m.fileId);await delOne('logs',l.id)}}logs=(await getAll('logs')).sort((a,b)=>b.updatedAt-a.updatedAt);for(const l of logs.slice(MAX_LOGS)){if(!l.pinned){for(const m of l.messages||[]) if(m.fileId) await delOne('files',m.fileId);await delOne('logs',l.id)}}}
async function ensureLog(peerId,peerName){let l=await getOne('logs',peerId);if(!l){l={id:peerId,peerName,createdAt:now(),updatedAt:now(),pinned:false,messages:[]};await put('logs',l)}return l}
async function addLogMessage(peerId,peerName,msg){const l=await ensureLog(peerId,peerName);l.peerName=peerName;l.updatedAt=now();l.messages.push(msg);await put('logs',l)}

// UI mode/settings
$('#hostModeBtn').onclick=()=>setMode('host'); $('#joinModeBtn').onclick=()=>setMode('join');
function setMode(m){state.mode=m;$('#hostModeBtn').classList.toggle('active',m==='host');$('#joinModeBtn').classList.toggle('active',m==='join');$('#hostPanel').hidden=m!=='host';$('#joinPanel').hidden=m!=='join'}
$('#localName').value=state.localName; $('#nameCount').textContent=`${state.localName.length}/18`;
$('#localName').oninput=e=>$('#nameCount').textContent=`${e.target.value.length}/18`;
$('#saveSettingsBtn').onclick=()=>{const v=$('#localName').value.trim()||'localuser';if(v.length>18)return toast('Máximo 18 caracteres');state.localName=v;localStorage.setItem('c1_localName',v);toast('Ajustes guardados')};

// WebRTC helpers - no external STUN: optimized for same LAN/hotspot
const rtcConfig={iceServers:[]};
function waitIce(pc){return new Promise(resolve=>{if(pc.iceGatheringState==='complete')return resolve();const f=()=>{if(pc.iceGatheringState==='complete'){pc.removeEventListener('icegatheringstatechange',f);resolve()}};pc.addEventListener('icegatheringstatechange',f);setTimeout(resolve,3500)})}
function setupPC(pc, peerId, peerName, channel){const peer={pc,dc:channel,peerId,peerName,incoming:new Map()};state.peers.set(peerId,peer);channel.binaryType='arraybuffer';channel.onopen=()=>{toast(`${peerName} conectado`);refreshPeers();markSlot(peerName,true);updateStatus()};channel.onclose=()=>{refreshPeers();markSlot(peerName,false);updateStatus()};channel.onerror=()=>toast('Error en canal de datos');channel.onmessage=e=>handleData(peer,e.data);pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState)){refreshPeers();updateStatus()}};refreshPeers();return peer}
function markSlot(name,on){const b=$(`.slot-btn[data-slot="${name}"]`);if(b)b.classList.toggle('connected',on)}
function updateStatus(){const n=[...state.peers.values()].filter(p=>p.dc?.readyState==='open').length;$('#connectionStatus').textContent=n?`${n} dispositivo(s) conectado(s)`:'Sin conexión'}
function refreshPeers(){const sel=$('#peerSelect');const prev=state.selectedPeer;sel.innerHTML='';const open=[...state.peers.values()].filter(p=>p.dc?.readyState==='open');open.forEach(p=>{const o=document.createElement('option');o.value=p.peerId;o.textContent=p.peerName;sel.appendChild(o)});if(open.length){state.selectedPeer=open.some(p=>p.peerId===prev)?prev:open[0].peerId;sel.value=state.selectedPeer;$('#peerBadge').classList.add('online');renderCurrentChat()}else{state.selectedPeer='';$('#peerBadge').classList.remove('online');$('#messages').innerHTML='<div class="empty">Conecta un dispositivo para comenzar.</div>'} }
$('#peerSelect').onchange=e=>{state.selectedPeer=e.target.value;renderCurrentChat()};

$$('.slot-btn').forEach(b=>b.onclick=async()=>{try{state.currentSlot=b.dataset.slot;const peerId=`${b.dataset.slot}-${Date.now()}`;const pc=new RTCPeerConnection(rtcConfig);const dc=pc.createDataChannel('chat');setupPC(pc,peerId,b.dataset.slot,dc);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);$('#offerCode').value=enc({v:1,type:'offer',slot:b.dataset.slot,peerId,sdp:pc.localDescription.sdp});$('#answerCode').value='';toast(`Invitación para ${b.dataset.slot} creada`)}catch(e){console.error(e);toast('No se pudo crear la invitación')}});
$('#applyAnswerBtn').onclick=async()=>{try{const a=dec($('#answerCode').value);if(a.type!=='answer')throw 0;const peer=state.peers.get(a.peerId);if(!peer)throw 0;await peer.pc.setRemoteDescription({type:'answer',sdp:a.sdp});toast('Enlace finalizado. Esperando conexión…')}catch(e){toast('Respuesta inválida')}};
$('#createAnswerBtn').onclick=async()=>{try{const o=dec($('#joinOfferCode').value);if(o.type!=='offer'||!/^Dip0[1-3]$/.test(o.slot))throw 0;const pc=new RTCPeerConnection(rtcConfig);let peer;pc.ondatachannel=ev=>{peer=setupPC(pc,o.peerId,state.localName,ev.channel);state.joinPeer=peer};await pc.setRemoteDescription({type:'offer',sdp:o.sdp});const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await waitIce(pc);$('#joinAnswerCode').value=enc({v:1,type:'answer',slot:o.slot,peerId:o.peerId,sdp:pc.localDescription.sdp});toast(`Respuesta creada. En este equipo eres ${o.slot}`)}catch(e){console.error(e);toast('Invitación inválida')}};

async function copyText(el){if(!el.value)return toast('No hay código');await navigator.clipboard.writeText(el.value);toast('Código copiado')}
$('#copyOfferBtn').onclick=()=>copyText($('#offerCode'));$('#copyAnswerBtn').onclick=()=>copyText($('#joinAnswerCode'));
async function shareText(el,title){if(!el.value)return toast('No hay código');if(navigator.share)await navigator.share({title,text:el.value});else copyText(el)}
$('#shareOfferBtn').onclick=()=>shareText($('#offerCode'),'Invitación connection1toOne');$('#shareAnswerBtn').onclick=()=>shareText($('#joinAnswerCode'),'Respuesta connection1toOne');

// Chat + file transfer
$('#sendBtn').onclick=sendText;$('#messageInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendText()}};
async function sendText(){const txt=$('#messageInput').value.trim();const p=state.peers.get(state.selectedPeer);if(!txt)return;if(!p||p.dc.readyState!=='open')return toast('Selecciona un dispositivo conectado');const msg={kind:'text',id:crypto.randomUUID(),text:txt,from:state.localName,ts:now()};p.dc.send(JSON.stringify(msg));await addLogMessage(p.peerId,p.peerName,{...msg,mine:true});$('#messageInput').value='';renderCurrentChat()}
$('#fileInput').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;if(f.size>MAX_FILE)return toast('El archivo supera 50 MB');const p=state.peers.get(state.selectedPeer);if(!p||p.dc.readyState!=='open')return toast('Selecciona un dispositivo conectado');await sendFile(p,f)};
async function sendFile(p,file){const id=crypto.randomUUID(),chunk=16*1024;const meta={kind:'file-meta',id,name:file.name,size:file.size,mime:file.type||'application/octet-stream',from:state.localName,ts:now()};p.dc.send(JSON.stringify(meta));$('#fileProgress').hidden=false;for(let off=0;off<file.size;off+=chunk){while(p.dc.bufferedAmount>4*1024*1024) await new Promise(r=>setTimeout(r,20));const buf=await file.slice(off,off+chunk).arrayBuffer();p.dc.send(buf);$('#fileProgress div').style.width=`${Math.min(100,((off+buf.byteLength)/file.size)*100)}%`}p.dc.send(JSON.stringify({kind:'file-end',id}));await put('files',{id,blob:file,name:file.name,mime:file.type||'application/octet-stream',size:file.size,createdAt:now()});await addLogMessage(p.peerId,p.peerName,{...meta,mine:true,fileId:id});$('#fileProgress').hidden=true;$('#fileProgress div').style.width='0';renderCurrentChat();toast('Archivo enviado')}
async function handleData(peer,data){if(typeof data==='string'){let m;try{m=JSON.parse(data)}catch{return}if(m.kind==='text'){await addLogMessage(peer.peerId,peer.peerName,{...m,mine:false});if(state.selectedPeer===peer.peerId)renderCurrentChat()}else if(m.kind==='file-meta'){peer.incoming.set(m.id,{meta:m,chunks:[],received:0})}else if(m.kind==='file-end'){const x=peer.incoming.get(m.id);if(!x)return;const blob=new Blob(x.chunks,{type:x.meta.mime});await put('files',{id:m.id,blob,name:x.meta.name,mime:x.meta.mime,size:x.meta.size,createdAt:now()});await addLogMessage(peer.peerId,peer.peerName,{...x.meta,mine:false,fileId:m.id});peer.incoming.delete(m.id);if(state.selectedPeer===peer.peerId)renderCurrentChat();toast('Archivo recibido')}}else{const x=[...peer.incoming.values()].at(-1);if(x){x.chunks.push(data);x.received+=data.byteLength}}}
async function renderCurrentChat(){const p=state.peers.get(state.selectedPeer);if(!p)return;const l=await getOne('logs',p.peerId);renderMessages(l?.messages||[])}
function renderMessages(messages){const box=$('#messages');box.innerHTML='';if(!messages.length){box.innerHTML='<div class="empty">Aún no hay mensajes.</div>';return}for(const m of messages){const d=document.createElement('div');d.className='bubble '+(m.mine?'mine':'theirs');if(m.kind==='text')d.textContent=m.text;else{const wrap=document.createElement('div');wrap.className='file-card';wrap.innerHTML=`📄 <button data-file="${m.fileId}">${escapeHtml(m.name)}</button> <span>${fmtBytes(m.size)}</span>`;d.appendChild(wrap)}const s=document.createElement('small');s.textContent=new Date(m.ts).toLocaleString();d.appendChild(s);box.appendChild(d)}box.scrollTop=box.scrollHeight;box.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>openFile(b.dataset.file))}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fmtBytes(n){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'}

// Bitácora
async function renderLogs(){await cleanup();const logs=(await getAll('logs')).sort((a,b)=>b.updatedAt-a.updatedAt);const box=$('#logList');box.innerHTML='';if(!logs.length){box.innerHTML='<div class="panel empty">No hay chats en la bitácora.</div>';return}for(const l of logs){const c=document.createElement('div');c.className='log-card';const expires=l.pinned?'Protegido':`Se borra en ${timeLeft(l.updatedAt+TTL)}`;c.innerHTML=`<div class="log-title"><strong>${escapeHtml(l.peerName)}</strong><label class="pin-wrap"><input type="checkbox" data-pin="${l.id}" ${l.pinned?'checked':''}> proteger</label></div><div class="log-meta">${l.messages.length} elemento(s) · ${expires}</div><div class="log-actions"><button data-openlog="${l.id}">Ver contenido</button><button data-del="${l.id}">Eliminar</button></div>`;box.appendChild(c)}box.querySelectorAll('[data-pin]').forEach(ch=>ch.onchange=async()=>{const logs=await getAll('logs'),l=logs.find(x=>x.id===ch.dataset.pin);if(!l)return;if(ch.checked&&logs.filter(x=>x.pinned).length>=MAX_PINNED){ch.checked=false;return toast('Solo puedes proteger 5 chats')}l.pinned=ch.checked;await put('logs',l);renderLogs()});box.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{const l=await getOne('logs',b.dataset.del);if(l)for(const m of l.messages||[])if(m.fileId)await delOne('files',m.fileId);await delOne('logs',b.dataset.del);renderLogs()});box.querySelectorAll('[data-openlog]').forEach(b=>b.onclick=async()=>{const l=await getOne('logs',b.dataset.openlog);if(l)openLogDialog(l)})}
function timeLeft(t){const ms=Math.max(0,t-now()),h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000);return `${h}h ${m}m`}
function openLogDialog(l){$('#previewTitle').textContent=`Bitácora · ${l.peerName}`;const body=$('#previewBody');body.innerHTML='';const wrap=document.createElement('div');wrap.className='messages';wrap.style.height='55vh';body.appendChild(wrap);renderMessagesInto(wrap,l.messages||[]);$('#previewDialog').showModal()}
function renderMessagesInto(box,messages){box.innerHTML='';for(const m of messages){const d=document.createElement('div');d.className='bubble '+(m.mine?'mine':'theirs');if(m.kind==='text')d.textContent=m.text;else d.innerHTML=`<div class="file-card">📄 <button data-file="${m.fileId}">${escapeHtml(m.name)}</button> <span>${fmtBytes(m.size)}</span></div>`;const s=document.createElement('small');s.textContent=new Date(m.ts).toLocaleString();d.appendChild(s);box.appendChild(d)}box.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>openFile(b.dataset.file))}
async function openFile(id){const f=await getOne('files',id);if(!f)return toast('Archivo no disponible');const url=URL.createObjectURL(f.blob);$('#previewTitle').textContent=f.name;const b=$('#previewBody');b.innerHTML='';if(f.mime.startsWith('image/')){const img=new Image();img.src=url;b.appendChild(img)}else if(f.mime.startsWith('video/')){const v=document.createElement('video');v.src=url;v.controls=true;b.appendChild(v)}else if(f.mime.startsWith('audio/')){const a=document.createElement('audio');a.src=url;a.controls=true;b.appendChild(a)}else{const a=document.createElement('a');a.href=url;a.download=f.name;a.textContent='Descargar / abrir archivo';b.appendChild(a)}$('#previewDialog').showModal();$('#previewDialog').addEventListener('close',()=>URL.revokeObjectURL(url),{once:true})}
$('#closePreview').onclick=()=>$('#previewDialog').close();

// PWA
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$('#installBtn').hidden=false});
$('#installBtn').onclick=async()=>{if(!state.deferredPrompt)return;state.deferredPrompt.prompt();await state.deferredPrompt.userChoice;state.deferredPrompt=null;$('#installBtn').hidden=true};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
cleanup();
